[[repos]]
repo = "local"
hooks = [
    {
        id = "lc_soln_readme",
        name = "lc_soln_readme",
        language = "system",
        entry = "python3 scripts/gen-readme.py",
        files = "lc_soln/*"
    }
]
