[package]
name = "false-rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "false"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
