[package]
name = "ctl-cli"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
ctl-aws-types = { workspace = true }

clap = { workspace = true }
