[package]
name = "ctl-dirs"
version = "0.1.0"
edition = { workspace = true }
rust-version = { workspace = true }

[lints]
workspace = true

[dependencies]
etcetera = { workspace = true }
thiserror = { workspace = true }
